Repository artesaos/seotools, pull requests merged in 2023-05, with the labels that each got.

#308 Temp Fix - PHPUnit 9
  composer.json
Labels: bug, high priority

#301 Add support to macro
  README.md
  src/SEOTools/SEOTools.php
Labels: feature

#299 #297 Updated OpenGraph Product attributes
  src/SEOTools/OpenGraph.php
Labels: feature, low priority
